name: yesssirbox
version: master-2.5
authors: [skaerf]
main: xyz.skaerf.yesssirbox.Yesssirbox
api-version: 1.18
depend: [Vault]
commands:
  yesssirbox:
    usage: /yesssirbox <reload/addBlock> [value]
    aliases: [yb,ysb]
  discord:
    usage: /discord
  shop:
    usage: /shop
  bounty:
    usage: /bounty